/* ---------- DataFrame / analytics ---------- */
static int df_is(Value v){Value t=v.t==VSTRUCT?stget(v.u.st,"__type"):vn();return t.t==VSTR&&!strcmp(t.u.s,"dataframe");}
static Value df_rows_v(Value v){return stget(v.u.st,"rows");}
static Value df_cols_v(Value v){return stget(v.u.st,"columns");}
static Value df_make(Value rows,Value cols){Value o=vsobj();stput(o.u.st,"__type",vs("dataframe"));stput(o.u.st,"rows",rows);stput(o.u.st,"columns",cols);stput(o.u.st,"nrows",vi((long long)rows.u.a->n));stput(o.u.st,"ncols",vi((long long)cols.u.a->n));return o;}
static Value data_coerce_cell(const char*s){if(!s)return vn();char*b=(char*)s;while(isspace((unsigned char)*b))b++;size_t L=strlen(b);while(L&&isspace((unsigned char)b[L-1]))b[--L]=0;if(!L||!strcasecmp(b,"null"))return vn();if(!strcasecmp(b,"true"))return vb(1);if(!strcasecmp(b,"false"))return vb(0);char*e=0;errno=0;long long i=strtoll(b,&e,10);if(errno==0&&e&&!*e)return vi(i);errno=0;double f=strtod(b,&e);if(errno==0&&e&&!*e&&isfinite(f))return vf(f);return vs(b);}
static Value data_csv_parse_text(const char*s,int header){Value rows=va(), cols=va();DBuf cell;dbuf_init(&cell);Value row=va();int inq=0;size_t i=0;int saw_any=0;while(s&&s[i]){char c=s[i++];if(inq){if(c=='"'){if(s[i]=='"'){dbuf_putc(&cell,'"');i++;}else inq=0;}else dbuf_putc(&cell,c);}else if(c=='"'){inq=1;saw_any=1;}else if(c==','){ap(row.u.a,data_coerce_cell(cell.d?cell.d:""));cell.n=0;if(cell.d)cell.d[0]=0;saw_any=1;}else if(c=='\n'||c=='\r'){if(c=='\r'&&s[i]=='\n')i++;ap(row.u.a,data_coerce_cell(cell.d?cell.d:""));cell.n=0;if(cell.d)cell.d[0]=0;if(saw_any||row.u.a->n>1){ap(rows.u.a,row);row=va();}saw_any=0;}else{dbuf_putc(&cell,c);saw_any=1;}}
if(saw_any||row.u.a->n){ap(row.u.a,data_coerce_cell(cell.d?cell.d:""));ap(rows.u.a,row);}if(cell.d)free(cell.d);
if(rows.u.a->n&&header){Value h=rows.u.a->v[0];if(h.t==VARR){for(size_t j=0;j<h.u.a->n;j++){Value x=h.u.a->v[j];if(x.t==VSTR)ap(cols.u.a,x);else{char z[32];snprintf(z,sizeof z,"col%zu",j);ap(cols.u.a,vs(z));}}Value body=va();for(size_t r=1;r<rows.u.a->n;r++)ap(body.u.a,rows.u.a->v[r]);return df_make(body,cols);}}
size_t m=rows.u.a->n?rows.u.a->v[0].u.a->n:0;for(size_t j=0;j<m;j++){char z[32];snprintf(z,sizeof z,"col%zu",j);ap(cols.u.a,vs(z));}return df_make(rows,cols);}
static Value data_read_csv(VM*vm,int n,Value*a){if(!cap_allowed(vm,CAP_FS))return cap_error(vm,CAP_FS,"data.read_csv");if(n<1||n>2||a[0].t!=VSTR)return vn();char*b=readf_limit(a[0].u.s,H_DATA_MAX);if(!b)return vn();int header=n==1?1:(a[1].t==VBOOL?a[1].u.b:1);Value v=data_csv_parse_text(b,header);xfree(b);return v;}
static Value data_from_rows(VM*vm,int n,Value*a){(void)vm;if(n<1||n>2||a[0].t!=VARR)return vn();Value rows=a[0],cols=n==2&&a[1].t==VARR?a[1]:va();if(n<2){size_t m=rows.u.a->n&&rows.u.a->v[0].t==VARR?rows.u.a->v[0].u.a->n:0;for(size_t j=0;j<m;j++){char z[32];snprintf(z,sizeof z,"col%zu",j);ap(cols.u.a,vs(z));}}return df_make(rows,cols);}
static Value data_rows(VM*vm,int n,Value*a){(void)vm;if(n==1&&df_is(a[0])){Value r=df_rows_v(a[0]);return r;}if(n==2&&df_is(a[0])&&a[1].t==VSTR&&!strcmp(a[1].u.s,"shape")){Value r=df_rows_v(a[0]);Value c=df_cols_v(a[0]);Value o=va();ap(o.u.a,vi((long long)(r.t==VARR?r.u.a->n:0)));ap(o.u.a,vi((long long)(c.t==VARR?c.u.a->n:0)));return o;}return vn();}
static Value data_shape(VM*vm,int n,Value*a){(void)vm;if(n!=1||!df_is(a[0]))return vn();Value r=df_rows_v(a[0]);Value c=df_cols_v(a[0]);Value o=va();ap(o.u.a,vi((long long)(r.t==VARR?r.u.a->n:0)));ap(o.u.a,vi((long long)(c.t==VARR?c.u.a->n:0)));return o;}
static int df_col_index(Value df,const char*name){Value c=df_cols_v(df);if(c.t!=VARR)return -1;for(size_t i=0;i<c.u.a->n;i++)if(c.u.a->v[i].t==VSTR&&!strcmp(c.u.a->v[i].u.s,name))return (int)i;return -1;}
static Value data_column(VM*vm,int n,Value*a){(void)vm;if((n!=2&&n!=3)||!df_is(a[0])||a[1].t!=VSTR)return vn();int ci=df_col_index(a[0],a[1].u.s);if(ci<0)return va();Value rows=df_rows_v(a[0]),out=va();for(size_t r=0;r<rows.u.a->n;r++){Value row=rows.u.a->v[r];ap(out.u.a,row.t==VARR&&(size_t)ci<row.u.a->n?row.u.a->v[ci]:vn());}if(n==3&&a[2].t==VBOOL&&a[2].u.b){Value z=va();for(size_t i=0;i<out.u.a->n;i++)if(isnum(out.u.a->v[i]))ap(z.u.a,out.u.a->v[i]);return z;}return out;}
static int df_match(Value x,const char*op,Value v){if(!op)return 0;if(!strcmp(op,"=="))return x.t==v.t?(x.t==VINT?x.u.i==v.u.i:x.t==VFLOAT?x.u.f==v.u.f:x.t==VBOOL?x.u.b==v.u.b:x.t==VSTR&&!strcmp(x.u.s,v.u.s)):((isnum(x)&&isnum(v))?dn(x)==dn(v):0);if(!strcmp(op,"!="))return !df_match(x,"==",v);if(!strcmp(op,"contains"))return x.t==VSTR&&v.t==VSTR&&strstr(x.u.s,v.u.s)!=NULL;if(isnum(x)&&isnum(v)){double a=dn(x),b=dn(v);if(!strcmp(op,">"))return a>b;if(!strcmp(op,"<"))return a<b;if(!strcmp(op,">="))return a>=b;if(!strcmp(op,"<="))return a<=b;}if(x.t==VSTR&&v.t==VSTR){int c=strcmp(x.u.s,v.u.s);if(!strcmp(op,">"))return c>0;if(!strcmp(op,"<"))return c<0;if(!strcmp(op,">="))return c>=0;if(!strcmp(op,"<="))return c<=0;}return 0;}
static Value data_filter(VM*vm,int n,Value*a){(void)vm;if(n!=4||!df_is(a[0])||a[1].t!=VSTR||a[2].t!=VSTR)return vn();int ci=df_col_index(a[0],a[1].u.s);if(ci<0)return data_from_rows(vm,1,(Value[]){va()});Value rows=df_rows_v(a[0]),out=va();for(size_t r=0;r<rows.u.a->n;r++){Value row=rows.u.a->v[r];if(row.t==VARR&&(size_t)ci<row.u.a->n&&df_match(row.u.a->v[ci],a[2].u.s,a[3]))ap(out.u.a,row);}return df_make(out,df_cols_v(a[0]));}
static Value data_sort(VM*vm,int n,Value*a){(void)vm;if(n<2||n>3||!df_is(a[0])||a[1].t!=VSTR)return vn();int ci=df_col_index(a[0],a[1].u.s);if(ci<0)return a[0];int desc=n==3&&a[2].t==VBOOL?a[2].u.b:0;Value out=va();Value rows=df_rows_v(a[0]);for(size_t i=0;i<rows.u.a->n;i++)ap(out.u.a,rows.u.a->v[i]);for(size_t i=1;i<out.u.a->n;i++){Value key=out.u.a->v[i];size_t j=i;while(j>0){Value prev=out.u.a->v[j-1],kx=key.t==VARR&&(size_t)ci<key.u.a->n?key.u.a->v[ci]:vn(),px=prev.t==VARR&&(size_t)ci<prev.u.a->n?prev.u.a->v[ci]:vn();int less=0;if(isnum(kx)&&isnum(px))less=dn(kx)<dn(px);else if(kx.t==VSTR&&px.t==VSTR)less=strcmp(kx.u.s,px.u.s)<0;if(desc)less=!less&&!df_match(kx,"==",px);if(!less)break;out.u.a->v[j]=out.u.a->v[j-1];j--;}out.u.a->v[j]=key;}return df_make(out,df_cols_v(a[0]));}
static Value data_head(VM*vm,int n,Value*a){(void)vm;if((n!=1&&n!=2)||!df_is(a[0]))return vn();long long k=n==2&&a[1].t==VINT?a[1].u.i:5;if(k<0)k=0;Value rows=df_rows_v(a[0]),out=va();size_t m=(size_t)(k<(long long)rows.u.a->n?k:rows.u.a->n);for(size_t i=0;i<m;i++)ap(out.u.a,rows.u.a->v[i]);return df_make(out,df_cols_v(a[0]));}
static Value data_tail(VM*vm,int n,Value*a){(void)vm;if((n!=1&&n!=2)||!df_is(a[0]))return vn();long long k=n==2&&a[1].t==VINT?a[1].u.i:5;if(k<0)k=0;Value rows=df_rows_v(a[0]),out=va();size_t start=rows.u.a->n>(size_t)k?rows.u.a->n-(size_t)k:0;for(size_t i=start;i<rows.u.a->n;i++)ap(out.u.a,rows.u.a->v[i]);return df_make(out,df_cols_v(a[0]));}
static Value data_describe(VM*vm,int n,Value*a){(void)vm;if(n!=1||!df_is(a[0]))return vn();Value rows=df_rows_v(a[0]),cols=df_cols_v(a[0]),out=vsobj();for(size_t ci=0;ci<cols.u.a->n;ci++){if(cols.u.a->v[ci].t!=VSTR)continue;long long cnt=0,miss=0;double sum=0,mn=INFINITY,mx=-INFINITY;for(size_t r=0;r<rows.u.a->n;r++){Value row=rows.u.a->v[r];Value x=(row.t==VARR&&ci<row.u.a->n)?row.u.a->v[ci]:vn();if(isnum(x)){double z=dn(x);cnt++;sum+=z;if(z<mn)mn=z;if(z>mx)mx=z;}else miss++;}Value st=vsobj();double mean=cnt?sum/(double)cnt:0,var=0;for(size_t r=0;r<rows.u.a->n;r++){Value row=rows.u.a->v[r];Value x=(row.t==VARR&&ci<row.u.a->n)?row.u.a->v[ci]:vn();if(isnum(x)){double d=dn(x)-mean;var+=d*d;}}stput(st.u.st,"count",vi(cnt));stput(st.u.st,"missing",vi(miss));stput(st.u.st,"mean",vf(mean));stput(st.u.st,"std",vf(cnt?sqrt(var/(double)cnt):0));stput(st.u.st,"min",vf(cnt?mn:0));stput(st.u.st,"max",vf(cnt?mx:0));stput(st.u.st,"sum",vf(sum));stput(out.u.st,cols.u.a->v[ci].u.s,st);}return out;}
static Value data_group_count(VM*vm,int n,Value*a){(void)vm;if(n!=2||!df_is(a[0])||a[1].t!=VSTR)return vn();int ci=df_col_index(a[0],a[1].u.s);if(ci<0)return va();Value rows=df_rows_v(a[0]),out=va();for(size_t i=0;i<rows.u.a->n;i++){Value row=rows.u.a->v[i];Value key=(row.t==VARR&&(size_t)ci<row.u.a->n)?row.u.a->v[ci]:vn();int found=-1;for(size_t j=0;j<out.u.a->n;j++){Value o=out.u.a->v[j];if(o.t==VSTRUCT&&df_match(stget(o.u.st,"key"),"==",key)){found=(int)j;break;}}if(found>=0){Value o=out.u.a->v[found];Value c=stget(o.u.st,"count");stput(o.u.st,"count",vi(c.t==VINT?c.u.i+1:1));}else{Value o=vsobj();stput(o.u.st,"key",key);stput(o.u.st,"count",vi(1));ap(out.u.a,o);}}return out;}
static Value data_drop_missing(VM*vm,int n,Value*a){(void)vm;if(n!=1||!df_is(a[0]))return vn();Value rows=df_rows_v(a[0]),out=va();for(size_t r=0;r<rows.u.a->n;r++){Value row=rows.u.a->v[r];int ok=1;if(row.t==VARR)for(size_t c=0;c<row.u.a->n;c++)if(row.u.a->v[c].t==VNULL){ok=0;break;}if(ok)ap(out.u.a,row);}return df_make(out,df_cols_v(a[0]));}
static Value data_fill_missing(VM*vm,int n,Value*a){(void)vm;if(n!=2||!df_is(a[0]))return vn();Value rows=df_rows_v(a[0]),out=va();for(size_t r=0;r<rows.u.a->n;r++){Value src=rows.u.a->v[r],row=va();if(src.t!=VARR)continue;for(size_t c=0;c<src.u.a->n;c++)ap(row.u.a,src.u.a->v[c].t==VNULL?a[1]:src.u.a->v[c]);ap(out.u.a,row);}return df_make(out,df_cols_v(a[0]));}
static Value data_sample(VM*vm,int n,Value*a){if(n<2||n>3||!df_is(a[0])||a[1].t!=VINT)return vn();long long k=a[1].u.i;if(k<0)k=0;
    if(n==3&&a[2].t==VINT)hr_rng_seed(vm,(uint64_t)a[2].u.i);
    Value rows=df_rows_v(a[0]),out=va();if((size_t)k>=rows.u.a->n){for(size_t i=0;i<rows.u.a->n;i++)ap(out.u.a,rows.u.a->v[i]);return df_make(out,df_cols_v(a[0]));}int*idx=(int*)malloc(rows.u.a->n*sizeof(int));if(!idx)return vn();for(size_t i=0;i<rows.u.a->n;i++)idx[i]=(int)i;for(size_t i=rows.u.a->n-1;i>0;i--){size_t j=(size_t)(hr_rng_next(vm)%(uint64_t)(i+1));int t=idx[i];idx[i]=idx[j];idx[j]=t;}for(long long i=0;i<k;i++)ap(out.u.a,rows.u.a->v[idx[i]]);free(idx);return df_make(out,df_cols_v(a[0]));}
static Value data_write_csv(VM*vm,int n,Value*a){if(!cap_allowed(vm,CAP_FS))return cap_error(vm,CAP_FS,"data.to_csv");if(n!=2||!df_is(a[0])||a[1].t!=VSTR)return vb(0);FILE*f=fopen(a[1].u.s,"wb");if(!f)return vb(0);Value cols=df_cols_v(a[0]);for(size_t c=0;c<cols.u.a->n;c++){if(c)fputc(',',f);fprintf(f,"\"%s\"",cols.u.a->v[c].u.s);}fputc('\n',f);Value rows=df_rows_v(a[0]);for(size_t r=0;r<rows.u.a->n;r++){Value row=rows.u.a->v[r];for(size_t c=0;c<cols.u.a->n;c++){if(c)fputc(',',f);Value x=(row.t==VARR&&c<row.u.a->n)?row.u.a->v[c]:vn();if(x.t==VNULL)continue;if(x.t==VSTR){fputc('"',f);for(const char*p=x.u.s;*p;p++){if(*p=='"')fputc('"',f);fputc(*p,f);}fputc('"',f);}else if(x.t==VINT)fprintf(f,"%lld",x.u.i);else if(x.t==VFLOAT)fprintf(f,"%.17g",x.u.f);else if(x.t==VBOOL)fputs(x.u.b?"true":"false",f);else fputs("null",f);}fputc('\n',f);}int rc=fclose(f);return vb(rc==0);}
static int data_numvec(Value v,double**out,size_t*nn){if(v.t!=VARR)return 0;double*p=(double*)malloc(v.u.a->n*sizeof(double));if(v.u.a->n&&!p)return 0;size_t k=0;for(size_t i=0;i<v.u.a->n;i++)if(isnum(v.u.a->v[i]))p[k++]=dn(v.u.a->v[i]);*out=p;*nn=k;return 1;}
static Value data_corr(VM*vm,int n,Value*a){(void)vm;if(n!=2)return vn();double*x=0,*y=0;size_t nx=0,ny=0;if(!data_numvec(a[0],&x,&nx)||!data_numvec(a[1],&y,&ny)){free(x);free(y);return vn();}size_t m=nx<ny?nx:ny;if(m<2){free(x);free(y);return vf(0);}double sx=0,sy=0;for(size_t i=0;i<m;i++){sx+=x[i];sy+=y[i];}double mx=sx/m,my=sy/m,xx=0,yy=0,xy=0;for(size_t i=0;i<m;i++){double dx=x[i]-mx,dy=y[i]-my;xx+=dx*dx;yy+=dy*dy;xy+=dx*dy;}free(x);free(y);return vf(xx&&yy?xy/sqrt(xx*yy):0);}
static Value data_cov(VM*vm,int n,Value*a){(void)vm;if(n!=2)return vn();double*x=0,*y=0;size_t nx=0,ny=0;if(!data_numvec(a[0],&x,&nx)||!data_numvec(a[1],&y,&ny)){free(x);free(y);return vn();}size_t m=nx<ny?nx:ny;if(m<2){free(x);free(y);return vf(0);}double sx=0,sy=0;for(size_t i=0;i<m;i++){sx+=x[i];sy+=y[i];}double mx=sx/m,my=sy/m,s=0;for(size_t i=0;i<m;i++)s+=(x[i]-mx)*(y[i]-my);free(x);free(y);return vf(s/(double)(m-1));}
static Value data_regression(VM*vm,int n,Value*a){(void)vm;if(n!=2)return vn();double*x=0,*y=0;size_t nx=0,ny=0;if(!data_numvec(a[0],&x,&nx)||!data_numvec(a[1],&y,&ny)){free(x);free(y);return vn();}size_t m=nx<ny?nx:ny;if(m<2){free(x);free(y);return vn();}double sx=0,sy=0,sxx=0,sxy=0;for(size_t i=0;i<m;i++){sx+=x[i];sy+=y[i];sxx+=x[i]*x[i];sxy+=x[i]*y[i];}double den=m*sxx-sx*sx;double slope=0, intercept=0; if(den){slope=(sxy*m-sx*sy)/den;intercept=(sy-slope*sx)/m;}double ssr=0,sst=0,ym=sy/m;for(size_t i=0;i<m;i++){double pred=intercept+slope*x[i];ssr+=(y[i]-pred)*(y[i]-pred);sst+=(y[i]-ym)*(y[i]-ym);}Value o=vsobj();stput(o.u.st,"slope",vf(slope));stput(o.u.st,"intercept",vf(intercept));stput(o.u.st,"r2",vf(sst>0?1-ssr/sst:0));free(x);free(y);return o;}
static Value data_zscore(VM*vm,int n,Value*a){(void)vm;if(n!=1||a[0].t!=VARR)return vn();double s=0;size_t c=0;for(size_t i=0;i<a[0].u.a->n;i++)if(isnum(a[0].u.a->v[i])){s+=dn(a[0].u.a->v[i]);c++;}double m=c?s/c:0,v=0;for(size_t i=0;i<a[0].u.a->n;i++)if(isnum(a[0].u.a->v[i])){double d=dn(a[0].u.a->v[i])-m;v+=d*d;}double sd=c?sqrt(v/c):1;Value o=va();for(size_t i=0;i<a[0].u.a->n;i++){Value x=a[0].u.a->v[i];ap(o.u.a,isnum(x)?vf((dn(x)-m)/(sd?sd:1)):vn());}return o;}
static Value data_minmax(VM*vm,int n,Value*a){(void)vm;if(n!=1||a[0].t!=VARR)return vn();double mn=INFINITY,mx=-INFINITY;for(size_t i=0;i<a[0].u.a->n;i++)if(isnum(a[0].u.a->v[i])){double x=dn(a[0].u.a->v[i]);if(x<mn)mn=x;if(x>mx)mx=x;}Value o=va();double d=(mx>mn)?mx-mn:1;for(size_t i=0;i<a[0].u.a->n;i++){Value x=a[0].u.a->v[i];ap(o.u.a,isnum(x)?vf((dn(x)-mn)/d):vn());}return o;}
static Value data_jsonl(VM*vm,int n,Value*a){if(!cap_allowed(vm,CAP_FS))return cap_error(vm,CAP_FS,"data.read_jsonl");if(n!=1||a[0].t!=VSTR)return vn();char*b=readf_limit(a[0].u.s,H_DATA_MAX);if(!b)return vn();Value out=va();char*save=0;for(char*line=strtok_r(b,"\n",&save);line;line=strtok_r(NULL,"\n",&save)){char*t=trim(line);if(!*t)continue;Value args[1]={vs(t)};Value row=njson_parse(vm,1,args);ap(out.u.a,row);}xfree(b);return out;}

