/* -------- ONNX protobuf subset: import/export for common float graphs -------- */
typedef struct {const unsigned char*p;size_t n,pos;} HPB;
static int hpb_varint(HPB*b,uint64_t*v){uint64_t x=0;int sh=0;while(b->pos<b->n&&sh<70){unsigned char c=b->p[b->pos++];x|=((uint64_t)(c&127))<<sh;if(!(c&128)){*v=x;return 1;}sh+=7;}return 0;}
static int hpb_field(HPB*b,int*f,int*w){uint64_t k;if(!hpb_varint(b,&k))return 0;*f=(int)(k>>3);*w=(int)(k&7);return *f>0;}
static int hpb_bytes(HPB*b,const unsigned char**p,size_t*n){uint64_t z;if(!hpb_varint(b,&z)||z>b->n-b->pos)return 0;*p=b->p+b->pos;*n=(size_t)z;b->pos+=(size_t)z;return 1;}
static int hpb_skip(HPB*b,int w){if(w==0){uint64_t x;return hpb_varint(b,&x);}if(w==1){if(b->n-b->pos<8)return 0;b->pos+=8;return 1;}if(w==2){const unsigned char*p;size_t n;return hpb_bytes(b,&p,&n);}if(w==5){if(b->n-b->pos<4)return 0;b->pos+=4;return 1;}return 0;}
static Value hpb_strings(HPB*b,int wantfield){Value a=va();while(b->pos<b->n){size_t save=b->pos;int f,w;if(!hpb_field(b,&f,&w))break;if(f!=wantfield){if(!hpb_skip(b,w))break;continue;}if(w!=2){if(!hpb_skip(b,w))break;continue;}const unsigned char*p;size_t z;if(!hpb_bytes(b,&p,&z))break;char*q=(char*)xmalloc(z+1);memcpy(q,p,z);q[z]=0;ap(a.u.a,vs(q));xfree(q);(void)save;}return a;}
static Value onnx_parse_tensor(const unsigned char*p,size_t n){HPB b={p,n,0};Value o=vsobj(),dims=va(),data=va();char name[256]={0};int dtype=0;const unsigned char*raw=NULL;size_t raw_n=0;while(b.pos<b.n){int f,w;if(!hpb_field(&b,&f,&w))break;if(f==1&&w==0){uint64_t x;if(!hpb_varint(&b,&x))break;ap(dims.u.a,vi((long long)x));}else if(f==2&&w==0){uint64_t x;if(!hpb_varint(&b,&x))break;dtype=(int)x;}else if(f==4&&w==5){if(b.n-b.pos<4)break;float x;memcpy(&x,b.p+b.pos,4);b.pos+=4;ap(data.u.a,vf(x));}else if(f==8&&w==2){const unsigned char*q;size_t z;if(!hpb_bytes(&b,&q,&z)||z>=sizeof name)break;memcpy(name,q,z);name[z]=0;}else if(f==9&&w==2){if(!hpb_bytes(&b,&raw,&raw_n))break;}else if(!hpb_skip(&b,w))break;}if(raw&&dtype==1&&raw_n%4==0&&raw_n/4<4000000ULL)for(size_t i=0;i<raw_n/4;i++){float x;memcpy(&x,raw+i*4,4);ap(data.u.a,vf(x));}stput(o.u.st,"name",vs(name));stput(o.u.st,"dtype",vi(dtype));stput(o.u.st,"dims",dims);stput(o.u.st,"data",data);return o;}
static Value ai_onnx_import(VM*vm,int n,Value*a){if(!cap_allowed(vm,CAP_FS))return cap_error(vm,CAP_FS,"onnx.import");if(n!=1||a[0].t!=VSTR||!fs_path_allowed(vm,a[0].u.s))return vn();char*src=readf_limit(a[0].u.s,64ULL*1024*1024);if(!src)return vn();size_t sz=0;FILE*f=fopen(a[0].u.s,"rb");if(f){fseek(f,0,SEEK_END);long z=ftell(f);fclose(f);if(z>0)sz=(size_t)z;}if(!sz){xfree(src);return vn();}HPB b={(const unsigned char*)src,sz,0};Value model=vsobj(),nodes=va(),in=va(),out=va(),init=va();int ir=0,opset=0;while(b.pos<b.n){int fld,w;if(!hpb_field(&b,&fld,&w))break;if(fld==1&&w==0){uint64_t x;if(!hpb_varint(&b,&x))break;ir=(int)x;}else if(fld==8&&w==2){const unsigned char*p;size_t z;if(!hpb_bytes(&b,&p,&z))break;HPB ob={p,z,0};while(ob.pos<ob.n){int of,ow;if(!hpb_field(&ob,&of,&ow))break;if(of==2&&ow==0){uint64_t x;if(!hpb_varint(&ob,&x))break;opset=(int)x;}else if(!hpb_skip(&ob,ow))break;}}else if(fld==7&&w==2){const unsigned char*g;size_t gz;if(!hpb_bytes(&b,&g,&gz))break;HPB gb={g,gz,0};while(gb.pos<gb.n){int gf,gw;if(!hpb_field(&gb,&gf,&gw))break;const unsigned char*q;size_t qz;if(gf==1&&gw==2){if(!hpb_bytes(&gb,&q,&qz))break;HPB nb={q,qz,0};Value no=vsobj();while(nb.pos<nb.n){int nf,nw;if(!hpb_field(&nb,&nf,&nw))break;if(nf==4&&nw==2){const unsigned char*s;size_t z;if(!hpb_bytes(&nb,&s,&z))break;char*t=(char*)xmalloc(z+1);memcpy(t,s,z);t[z]=0;stput(no.u.st,"op",vs(t));xfree(t);}else if((nf==1||nf==2||nf==3)&&nw==2){const unsigned char*s;size_t z;if(!hpb_bytes(&nb,&s,&z))break;char*t=(char*)xmalloc(z+1);memcpy(t,s,z);t[z]=0;Value key=vs(nf==1?"input":(nf==2?"output":"name"));Value curv=stget(no.u.st,key.u.s);if(curv.t!=VARR)curv=va();ap(curv.u.a,vs(t));stput(no.u.st,key.u.s,curv);xfree(t);}else if(!hpb_skip(&nb,nw))break;}ap(nodes.u.a,no);}else if(gf==5&&gw==2){if(!hpb_bytes(&gb,&q,&qz))break;ap(init.u.a,onnx_parse_tensor(q,qz));}else if((gf==11||gf==12)&&gw==2){if(!hpb_bytes(&gb,&q,&qz))break;HPB vb={q,qz,0};char nm[256]={0};while(vb.pos<vb.n){int vf,vw;if(!hpb_field(&vb,&vf,&vw))break;if(vf==1&&vw==2){const unsigned char*s;size_t z;if(!hpb_bytes(&vb,&s,&z))break;if(z>=sizeof nm)break;memcpy(nm,s,z);nm[z]=0;}else if(!hpb_skip(&vb,vw))break;}if(nm[0])(gf==11?ap(in.u.a,vs(nm)):ap(out.u.a,vs(nm)));}else if(!hpb_skip(&gb,gw))break;}}else if(!hpb_skip(&b,w))break;}stput(model.u.st,"format",vs("ONNX"));stput(model.u.st,"ir_version",vi(ir));stput(model.u.st,"opset",vi(opset));stput(model.u.st,"nodes",nodes);stput(model.u.st,"initializers",init);stput(model.u.st,"inputs",in);stput(model.u.st,"outputs",out);stput(model.u.st,"supported_ops",vs("MatMul,Add,Relu"));stput(model.u.st,"weights_format",vs("float32/raw_data"));xfree(src);return model;}
static void onnx_put_var(DBuf*b,uint64_t x){unsigned char z[10];int n=0;do{z[n]=(unsigned char)(x&127);x>>=7;if(x)z[n]|=128;n++;}while(x);dbuf_putn(b,(const char*)z,(size_t)n);}
static void onnx_key(DBuf*b,int f,int w){onnx_put_var(b,((uint64_t)f<<3)|w);}
static void onnx_var(DBuf*b,int f,uint64_t x){onnx_key(b,f,0);onnx_put_var(b,x);}
static void onnx_bytes(DBuf*b,int f,const void*p,size_t n){onnx_key(b,f,2);onnx_put_var(b,n);dbuf_putn(b,p,n);}
static void onnx_str(DBuf*b,int f,const char*s){onnx_bytes(b,f,s,strlen(s));}
static void onnx_tensor(DBuf*b,const char*name,int d0,int d1,const double*src,int rows,int cols,int transpose){DBuf t={0},raw={0};for(int i=0;i<rows*cols;i++){float x=(float)(transpose?src[(i%rows)*cols+i/rows]:src[i]);dbuf_putn(&raw,(const char*)&x,4);}onnx_str(&t,8,name);onnx_var(&t,2,1);onnx_var(&t,1,(uint64_t)d0);onnx_var(&t,1,(uint64_t)d1);onnx_bytes(&t,9,raw.d,raw.n);onnx_bytes(b,5,t.d,t.n);if(raw.d)free(raw.d);if(t.d)free(t.d);}
static void onnx_value_info(DBuf*b,int field,const char*name,int d0,int d1){DBuf dim0={0},dim1={0},shape={0},tt={0},ty={0},vi={0};onnx_var(&dim0,1,(uint64_t)d0);onnx_var(&dim1,1,(uint64_t)d1);onnx_bytes(&shape,1,dim0.d,dim0.n);onnx_bytes(&shape,1,dim1.d,dim1.n);onnx_var(&tt,1,1);onnx_bytes(&tt,2,shape.d,shape.n);onnx_bytes(&ty,1,tt.d,tt.n);onnx_str(&vi,1,name);onnx_bytes(&vi,3,ty.d,ty.n);onnx_bytes(b,field,vi.d,vi.n);if(dim0.d)free(dim0.d);if(dim1.d)free(dim1.d);if(shape.d)free(shape.d);if(tt.d)free(tt.d);if(ty.d)free(ty.d);if(vi.d)free(vi.d);}
static Value ai_onnx_export_mlp(VM*vm,int n,Value*a){if(!cap_allowed(vm,CAP_FS))return cap_error(vm,CAP_FS,"onnx.export_mlp");if(n!=2||!hkind(a[0],HK_MLP)||a[1].t!=VSTR||!fs_path_allowed(vm,a[1].u.s))return vb(0);HMLP*m=a[0].u.handle;DBuf graph={0},model={0};onnx_str(&graph,2,"haris_mlp");onnx_value_info(&graph,11,"X",1,m->in);onnx_value_info(&graph,12,"Y",1,m->out);
    DBuf node={0};onnx_str(&node,1,"X");onnx_str(&node,1,"W1");onnx_str(&node,2,"Z1");onnx_str(&node,4,"MatMul");onnx_bytes(&graph,1,node.d,node.n);if(node.d)free(node.d);node.d=NULL;
    node.n=0;onnx_str(&node,1,"Z1");onnx_str(&node,1,"B1");onnx_str(&node,2,"A1");onnx_str(&node,4,"Add");onnx_bytes(&graph,1,node.d,node.n);if(node.d)free(node.d);node.d=NULL;
    node.n=0;onnx_str(&node,1,"A1");onnx_str(&node,2,"H");onnx_str(&node,4,"Relu");onnx_bytes(&graph,1,node.d,node.n);if(node.d)free(node.d);node.d=NULL;
    node.n=0;onnx_str(&node,1,"H");onnx_str(&node,1,"W2");onnx_str(&node,2,"Z2");onnx_str(&node,4,"MatMul");onnx_bytes(&graph,1,node.d,node.n);if(node.d)free(node.d);node.d=NULL;
    node.n=0;onnx_str(&node,1,"Z2");onnx_str(&node,1,"B2");onnx_str(&node,2,"Y");onnx_str(&node,4,"Add");onnx_bytes(&graph,1,node.d,node.n);if(node.d)free(node.d);
    onnx_tensor(&graph,"W1",m->in,m->hidden,m->w1,m->hidden,m->in,1);onnx_tensor(&graph,"B1",m->hidden,1,m->b1,m->hidden,1,0);onnx_tensor(&graph,"W2",m->hidden,m->out,m->w2,m->out,m->hidden,1);onnx_tensor(&graph,"B2",m->out,1,m->b2,m->out,1,0);
    onnx_str(&model,8,"ai.onnx");onnx_var(&model,1,8);onnx_var(&model,4,1);onnx_bytes(&model,7,graph.d,graph.n);DBuf ops={0};onnx_str(&ops,1,"");onnx_var(&ops,2,17);onnx_bytes(&model,8,ops.d,ops.n);FILE*f=fopen(a[1].u.s,"wb");int ok=0;if(f){ok=(fwrite(model.d,1,model.n,f)==model.n);if(fclose(f)!=0)ok=0;f=NULL;}if(graph.d)free(graph.d);if(model.d)free(model.d);if(ops.d)free(ops.d);return vb(ok);}
static Value ai_onnx_run(VM*vm,int n,Value*a){(void)vm;if(n!=2||a[0].t!=VSTRUCT||a[1].t!=VARR)return vn();Value model=a[0],nodes=stget(model.u.st,"nodes"),init=stget(model.u.st,"initializers"),X=a[1];if(nodes.t!=VARR||init.t!=VARR)return vn();Value vars=vsobj();stput(vars.u.st,"X",X);for(size_t ni=0;ni<nodes.u.a->n;ni++){Value nd=nodes.u.a->v[ni];if(nd.t!=VSTRUCT)continue;Value op=stget(nd.u.st,"op"),ins=stget(nd.u.st,"input"),outs=stget(nd.u.st,"output");if(op.t!=VSTR||ins.t!=VARR||outs.t!=VARR||outs.u.a->n<1)continue;Value in0=stget(vars.u.st,ins.u.a->v[0].u.s);Value getinit=stget(model.u.st,"initializers");(void)getinit;if(!strcmp(op.u.s,"Relu")){Value p=va();if(in0.t!=VARR)return vn();for(size_t i=0;i<in0.u.a->n;i++){Value row=in0.u.a->v[i];if(row.t!=VARR)return vn();Value rr=va();for(size_t j=0;j<row.u.a->n;j++)ap(rr.u.a,vf(fmax(0,dn(row.u.a->v[j]))));ap(p.u.a,rr);}stput(vars.u.st,outs.u.a->v[0].u.s,p);}else if(!strcmp(op.u.s,"MatMul")||!strcmp(op.u.s,"Add")){Value rhs=ins.u.a->n>1?stget(vars.u.st,ins.u.a->v[1].u.s):vn();if(rhs.t==VNULL){for(size_t ii=0;ii<init.u.a->n;ii++){Value t=init.u.a->v[ii];if(t.t==VSTRUCT&&stget(t.u.st,"name").t==VSTR&&!strcmp(stget(t.u.st,"name").u.s,ins.u.a->v[1].u.s)){rhs=stget(t.u.st,"data");Value dims=stget(t.u.st,"dims");if(dims.t==VARR&&dims.u.a->n==2){Value rr=va();size_t off=0;for(int rrn=0;rrn<(int)dims.u.a->v[0].u.i;rrn++){Value rrow=va();for(int cc=0;cc<(int)dims.u.a->v[1].u.i;cc++)ap(rrow.u.a,rhs.u.a->v[off++]);ap(rr.u.a,rrow);}rhs=rr;}break;}}}if(in0.t!=VARR||rhs.t!=VARR)return vn();Value result=va();if(!strcmp(op.u.s,"MatMul")){size_t M=in0.u.a->n,K=in0.u.a->v[0].u.a->n,N=rhs.u.a->v[0].u.a->n;for(size_t i=0;i<M;i++){Value r=va();for(size_t j=0;j<N;j++){double s=0;for(size_t k=0;k<K;k++)s+=dn(in0.u.a->v[i].u.a->v[k])*dn(rhs.u.a->v[k].u.a->v[j]);ap(r.u.a,vf(s));}ap(result.u.a,r);}}else{size_t rows=in0.u.a->n;for(size_t i=0;i<rows;i++){Value r=va();size_t cols=in0.u.a->v[i].u.a->n;for(size_t j=0;j<cols;j++){Value bv=vn();if(rhs.u.a->n==1&&rhs.u.a->v[0].t!=VARR)bv=rhs.u.a->v[0];else if(rhs.u.a->n==1&&rhs.u.a->v[0].t==VARR&&rhs.u.a->v[0].u.a->n==cols)bv=rhs.u.a->v[0].u.a->v[j];else if(rhs.u.a->n==rows&&rhs.u.a->v[i].t==VARR&&rhs.u.a->v[i].u.a->n==1)bv=rhs.u.a->v[i].u.a->v[0];else if(rhs.u.a->n==cols&&rhs.u.a->v[j].t==VARR&&rhs.u.a->v[j].u.a->n==1)bv=rhs.u.a->v[j].u.a->v[0];else if(rhs.u.a->n==1&&rhs.u.a->v[0].t==VARR&&rhs.u.a->v[0].u.a->n==1)bv=rhs.u.a->v[0].u.a->v[0];else return vn();if(!isnum(bv))return vn();ap(r.u.a,vf(dn(in0.u.a->v[i].u.a->v[j])+dn(bv)));}ap(result.u.a,r);}}stput(vars.u.st,outs.u.a->v[0].u.s,result);}}
    Value outs2=stget(model.u.st,"outputs");if(outs2.t==VARR&&outs2.u.a->n){Value r=stget(vars.u.st,outs2.u.a->v[0].u.s);if(r.t!=VNULL)return r;}return vn();}

